### ISSUE TITLE
Problems to solve to be perfect

### ISSUE THREAD

**Issue by prsolucoes** [prsolucoes/mobile-pdfium#1]
Hi,

I finished my script to build the PDFium to iOS. All is here with manual patchs:
https://github.com/prsolucoes/mobile-pdfium

It generate files:
```
- libpdfium_arm.a
- libpdfium_arm64.a
- libpdfium_x64.a
- libpdfium_x86.a
- libpdfium.a (universal)
```

**FIRST PROBLEM**

The problem is that i join all ".a" files on each library and each library have +/- 200MB and the universal near 1GB of size.

I want understand what libraries i need merge with libtool, i have this:

```
- pdfium/out/debug-arm/obj/libfpdfdoc.a
- pdfium/out/debug-arm/obj/libfxge.a
- pdfium/out/debug-arm/obj/libpdfium.a
- pdfium/out/debug-arm/obj/libfdrm.a
- pdfium/out/debug-arm/obj/libformfiller.a
- pdfium/out/debug-arm/obj/third_party/libjpeg_turbo/libsimd.a
- pdfium/out/debug-arm/obj/third_party/libjpeg_turbo/libjpeg.a
- pdfium/out/debug-arm/obj/third_party/libfx_agg.a
- pdfium/out/debug-arm/obj/third_party/zlib/libzlib_x86_simd.a
- pdfium/out/debug-arm/obj/third_party/zlib/libchrome_zlib.a
- pdfium/out/debug-arm/obj/third_party/libbigint.a
- pdfium/out/debug-arm/obj/third_party/libfx_freetype.a
- pdfium/out/debug-arm/obj/third_party/libfx_libopenjpeg.a
- pdfium/out/debug-arm/obj/third_party/libfx_lcms2.a
- pdfium/out/debug-arm/obj/third_party/icu/libicuuc.a
- pdfium/out/debug-arm/obj/libpwl.a
- pdfium/out/debug-arm/obj/libfpdftext.a
- pdfium/out/debug-arm/obj/libfpdfapi.a
- pdfium/out/debug-arm/obj/libfxcrt.a
- pdfium/out/debug-arm/obj/libfxcodec.a
- pdfium/out/debug-arm/obj/libfxjs.a
```

Today im merging all for each library and each arch and the library is with a huge file size.

**SECOND PROBLEM**

The libraries are compile always with iOS 10 and xcode give me 402 warning about it:

```
ld: warning: object file (/Users/paulo/Downloads/UXReader-iOS/UXReader/UXReader/PDFium/libpdfium.a(cpdf_formcontrol.o)) was built for newer iOS version (10.0) than being linked (8.0)
```

My project need be for iOS 8.0, but the libraries are compile with iOS 10.

How to solve it?

**THIRD PROBLEM**

I merge and link with all libraries (.a), but when i use with a sample project i still have some functions not linked inside the library ".a":

<img width="1015" alt="screenshot 2018-05-24 01 49 12" src="https://user-images.githubusercontent.com/395096/40465336-9f1bd062-5ef6-11e8-9190-f8a2fe5774fa.png">

**FOURTY PROBLEM**

How to build with bitcode support? How to enable and disable it?

**FINISH**

Can anyone help me with this problems?

Thanks.

**Comment by raghuwanshi** [comment]
Thank you for saving my time by providing this script. I am still working on this project but let me share the solution to your first problem. You can use these args:
```
is_debug=false
symbol_level=0
```
Please see the symbol_level documentation for further details. Although my need to build PDFium on iOS is for a different purpose and due to that I have some other issues rather than what you have mentioned here, I will see if can find any solution for them.

**Comment by prsolucoes** [comment]
The flag "is_debug" i already use.

![image](https://user-images.githubusercontent.com/395096/43471394-44fa4126-94c1-11e8-9ab1-30233f51e787.png)

**Comment by prsolucoes** [comment]
My first problem is about merge all that libraries. The file size is too big.

**Comment by raghuwanshi** [comment]
I hope that suggested change has also reduced the files sizes for you.

**Comment by hhartz** [comment]
@raghuwanshi maybe make a pull request?

**Comment by chml** [comment]
> THIRD PROBLEM
> 
> I merge and link with all libraries (.a), but when i use with a sample project i still have some functions not linked inside the library ".a":


Try change  file `third_party/BUILD.gn` line 539 `jumbo_source_set("pdfium_base") {` to `static_library("pdfium_base") {`, to get the `libpdfium_base.a`.

**Comment by raghuwanshi** [comment]
@chml I tried that but that did not fix all errors. Then I found the real solution. I will commit that and make a pull request.

**Comment by hhartz** [comment]
I use the following patch file, which also removes the need for the whole chromium checkout (as it doesn't build the iossim test); http://ix.io/1lvz

**Comment by hhartz** [comment]
@raghuwanshi did you manage to get `arm` to build with neon? I'm getting missing symbols

**Comment by raghuwanshi** [comment]
@hhartz I am using it for Xamarin.iOS. I was able to build my application for all four platforms i.e. ARM, ARM64, x86 and x64

**Comment by hhartz** [comment]
@raghuwanshi I'm getting linker issues for armv7, can you confirm your app builds when archiving, and that you have armv7 as one of the architectures?

```Undefined symbols for architecture armv7:
  "_jsimd_ycc_extrgb_convert_neon", referenced from:
      _jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extrgbx_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extxbgr_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_ifast_neon", referenced from:
      _jsimd_idct_ifast in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_2x2_neon", referenced from:
      _jsimd_idct_2x2 in libpdfium.a(jsimd_arm.o)
  "_jsimd_h2v1_fancy_upsample_neon", referenced from:
      _jsimd_h2v1_fancy_upsample in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extbgrx_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extxrgb_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_islow_neon", referenced from:
      _jsimd_idct_islow in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_4x4_neon", referenced from:
      _jsimd_idct_4x4 in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extbgr_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_rgb565_convert_neon", referenced from:
      _jsimd_ycc_rgb565_convert in libpdfium.a(jsimd_arm.o)
ld: symbol(s) not found for architecture armv7```

**Comment by prsolucoes** [comment]
I merged the pull request. but im still getting errors:

![image](https://user-images.githubusercontent.com/395096/44798169-44529e80-ab87-11e8-8dce-c2f7b6be76d1.png)

Generated PDFium release:
https://www.dropbox.com/s/7fvj5n8ryv00xpb/pdfium-release.zip?dl=1

Sample project:
https://github.com/vfr/UXReader-iOS

** replace "libpdfium.a" from project to lib inside "pdfium-release.zip".

**Comment by chml** [comment]
Add all these .a files, then it works
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1294665/44832949-0aed6200-ac5f-11e8-9fbb-fb805f3abd1c.png">

**Comment by prsolucoes** [comment]
But all .a files is inside the main .a file. They are merged.

**Comment by prsolucoes** [comment]
The problems in related to arm64. It is running fine on simulator. I think that zlib or something is not compiling to arm64.

**Comment by prsolucoes** [comment]
ARMv7:

```
Undefined symbols for architecture armv7:
  "_jsimd_ycc_extrgb_convert_neon", referenced from:
      _jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extbgr_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extbgrx_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extxrgb_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_Cr_z_inflateInit_", referenced from:
      (anonymous namespace)::FlateInit() in libpdfium.a(fx_codec_flate.o)
  "_jsimd_idct_islow_neon", referenced from:
      _jsimd_idct_islow in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_4x4_neon", referenced from:
      _jsimd_idct_4x4 in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_2x2_neon", referenced from:
      _jsimd_idct_2x2 in libpdfium.a(jsimd_arm.o)
  "_jsimd_h2v1_fancy_upsample_neon", referenced from:
      _jsimd_h2v1_fancy_upsample in libpdfium.a(jsimd_arm.o)
  "_jsimd_idct_ifast_neon", referenced from:
      _jsimd_idct_ifast in libpdfium.a(jsimd_arm.o)
  "_Cr_z_inflate", referenced from:
      (anonymous namespace)::FlateOutput(void*, unsigned char*, unsigned int) in libpdfium.a(fx_codec_flate.o)
  "_jsimd_ycc_rgb565_convert_neon", referenced from:
      _jsimd_ycc_rgb565_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extrgbx_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_jsimd_ycc_extxbgr_convert_neon", referenced from:
      l_switch.table.jsimd_ycc_rgb_convert in libpdfium.a(jsimd_arm.o)
  "_Cr_z_inflateEnd", referenced from:
      (anonymous namespace)::FlateEnd(void*) in libpdfium.a(fx_codec_flate.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

ARM64:

```
Undefined symbols for architecture arm64:
  "_Cr_z_inflate", referenced from:
      (anonymous namespace)::FlateOutput(void*, unsigned char*, unsigned int) in libpdfium.a(fx_codec_flate.o)
  "_Cr_z_inflateEnd", referenced from:
      (anonymous namespace)::FlateEnd(void*) in libpdfium.a(fx_codec_flate.o)
  "_Cr_z_inflateInit_", referenced from:
      (anonymous namespace)::FlateInit() in libpdfium.a(fx_codec_flate.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Changzw** [comment]
[libpdfium.a](https://pan.baidu.com/s/1ojQWo6qTnNUpMGgitmcu1w) <br>
password: bvy5<br>
it includes arm32, arm64, x86, x64.<br>
I will write the Tutorial by which you can compile it.<br>
P.S. for simulator, you should add libz.tbd to your target.

**Comment by hhartz** [comment]
I managed to get it building + running myself, by reverting the change that use libjpeg_turbo instead of libjpeg. @Changzw can you confirm it actually compiles if you archive a target which has armv7? in my experience it will fail due to having some specific SIMD symbols missing, even if `file libpdfium.a` tells you there is an armv7 segment

**Comment by prsolucoes** [comment]
@Changzw Put here what config you use to:

1 - Change the iOS version that library was built
2 - Include simd/z things that error happen.

Thanks.

**Comment by hhartz** [comment]
@prsolucoes In [this branch](https://github.com/reMarkable/pdfium-qmake/tree/henrik/armv7) you'll see instructions for how to build pdfium with working armv7. I took the liberty of copying your make.py (with attribution in the commit), and have a set of changes/reverts to make it work all outlined in the README.md. Basically it reverts the use of libjpeg_turbo to libjpeg. An improvement would be to only use that for arm and let it use libjpeg_turbo for other architectures, which I haven't gotten around to (yet). I played around with settings various compiler flags as mentioned in various threads, as well as adding gas-preprocessor.pl to PATH without any luck. Not a lasting solution, but it's the hammer that solves my issue at the moment :) The compiled binary can be fetched in iosprecompiled with `git lfs`

**Comment by Changzw** [comment]
> if you archive a target which has armv7?

I did it.
https://github.com/prsolucoes/mobile-pdfium/issues/1#issuecomment-420979097

**Comment by hhartz** [comment]
@Changzw As described in my earlier comments, I already have a working setup. Also, you should probably provide a build config instead, as people should have full control over the code they release to their customers.

**Comment by prsolucoes** [comment]
@hhartz Can you help me modify my script to build all with success? I want leave this repository as a reference to everyone that need it. After i will do the same for Android.

**Comment by Changzw** [comment]
it is a very huge project :( !  I not only change source code depended by pdfium, but also update UXReader code to support latest pdfium version and pdfium building config .  

Sorry, I don't have enough time to do this.

**Comment by peddamat** [comment]
I am unable to download the file from #1 (comment).  Unfortunately, I do not read Chinese, and attempting to translate the page using Google Translate results in a 404. : (

**Comment by Changzw** [comment]
> @Changzw I am unable to download the file from #1 (comment). Unfortunately, I do not read Chinese, and attempting to translate the page using Google Translate results in a 404. : ( Is there an alternative place that you can post it?

try [this](https://www.dropbox.com/sh/vn8oz5576agzoca/AABohTT3MrUatkL0K1hPa0ela?dl=0)

**Comment by peddamat** [comment]
@Changzw Thank you so much, I will report back with my results.

**Comment by prsolucoes** [comment]
Hi,

I solved all problems. It is working now. Check travis and new README file for instructions.

I something can be better, please report.

Thanks.

**Comment by prsolucoes** [comment]
Maybe someone could help here:
https://github.com/prsolucoes/mobile-pdfium/issues/4

**Comment by prsolucoes** [comment]
The main problem is here:
![image](https://user-images.githubusercontent.com/395096/69563313-a323e500-0f8f-11ea-9bcb-d5bcae21bbd5.png)

**Comment by prsolucoes** [comment]
Hi,

Problems solved. I have reimplemented read string methods from two files to solve memory bugs:
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_streamparser_modified.cpp
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_syntax_parser_modified.cpp

Now it is working very well on all devices.

Thanks.
