### ISSUE TITLE
release libpdfium.a files

### ISSUE THREAD

**Issue by Changzw** [prsolucoes/mobile-pdfium#2]
hi, I have tried 6 times to run build-pdfium,
but it's always going wrong
Can you release these libs to Github so that I can download, thx
---
the detail is below:
Downloading 1 files took 0.325647 second(s)
Error: Command 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s pdfium/buildtools/mac/gn.sha1' returned non-zero exit status 1 in /Users/changzhongwei/Github/peek/pdf/mobile-pdfium

**Comment by Changzw** [comment]
I solved it

**Comment by prsolucoes** [comment]
https://www.dropbox.com/s/5bds0rb8i0xklbs/pdfium-debug.zip?dl=0
