### ISSUE TITLE
Crashing on simulator (os=ios and cpu=x86_64)

### ISSUE THREAD

**Issue by prsolucoes** [prsolucoes/mobile-pdfium#5]
Everything is working fine on devices.

There is only **one** problem now on ios simulators, where **os=ios and cpu=x86_64**.

When PDF will open it crash here:

```
let pdfiumDocument = PDFiumDocument(url: "file.pdf", password: "")
```

![image](https://user-images.githubusercontent.com/395096/69176342-539f6e00-0ae4-11ea-8d51-64f5fc66593e.png)

![image](https://user-images.githubusercontent.com/395096/69176448-7d589500-0ae4-11ea-8893-9651b0f7f529.png)

Can someone help on this?

**Comment by prsolucoes** [comment]
The main problem is here:
![image](https://user-images.githubusercontent.com/395096/69563285-93a49c00-0f8f-11ea-9b80-4ec0188112d8.png)

**Comment by prsolucoes** [comment]
The var **ch** = "\xb6".

**Comment by prsolucoes** [comment]
Hi,

Problems solved. I have reimplemented read string methods from two files to solve memory bugs:
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_streamparser_modified.cpp
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_syntax_parser_modified.cpp

Now it is working very well on all devices.

Thanks.

**Comment by juliand665** [comment]
Thank you so much for all this great work you did! I'm sorry I wasn't more helpful, but it seems you've figured it out all by yourself in the end :)

**Comment by prsolucoes** [comment]
Ok,

**Comment by prsolucoes** [comment]
Hummm

I will rollback latest changes to use streams again and use your test project to test changes.

This sample can be used for it?

**Comment by juliand665** [comment]
Yeah, the example in #6 has both font-based and curve-based text, so that should help you test it. Otherwise, just using the example app in `mangelio/SimplePDFKit` works too; that's the same sample.

**Comment by prsolucoes** [comment]
Hi,

The updated binaries is here:
https://github.com/prsolucoes/mobile-pdfium

It works with your sample in simulator and device.

Get prebuilt library on end of file README.md at my repository.

Can you test it?

Thanks.
