### ISSUE TITLE
Text doesn't render anymore

### ISSUE THREAD

**Issue by juliand665** [prsolucoes/mobile-pdfium#6]
Before you fixed the simulator issues, I created a build of the library, which worked great on device ("before" image below), but in the process of fixing the simulator issues, something about the text rendering must have broken, because it now only renders the text i converted to curves rather than leaving it font-based ("after" image below).

before:
![image](https://user-images.githubusercontent.com/827762/69776094-29604700-119b-11ea-9860-2bafb8fdcdb7.png)
after:
![image](https://user-images.githubusercontent.com/827762/69776105-35e49f80-119b-11ea-9372-131624524468.png)

[Here](https://github.com/prsolucoes/mobile-pdfium/files/3899773/example.easy.pdf)'s the example I used here, which might come in handy for you; it's also the sample embedded in [SimplePDFKit](https://github.com/mangelio/SimplePDFKit), in case you've been using that (I only converted the "such vector" text to curves in the most recent revision, though).

**Comment by prsolucoes** [comment]
Hi,

The updated binaries is here:
https://github.com/prsolucoes/mobile-pdfium

It works with your sample in simulator and device.

Get prebuilt library on end of file README.md at my repository.

Thanks.

**Comment by prsolucoes** [comment]
Hi,

Also, can you test it?

Thanks.

**Comment by juliand665** [comment]
That worked perfectly! Love it. Will try building for myself now, but that shouldn't have any issues.

**Comment by juliand665** [comment]
Just built it myself and that worked too; very nice.
